#########################################################
# ClickVillagers Settings
# NOTE: RELOAD/RESTART SERVER FOR CHANGES TO TAKE EFFECT
#########################################################
config-version: 2
#########################################################

# Language of the plugin.
# Currently supported languages: en_US, de_DE
language: en_US

# Whether to check for updates on server startup.
# Strongly Recommended.
check-update: true

# Whether claimed villagers should take damage.
# Default: false
claimed-damage: false
# Whether claimed villagers should be immune to the /kill command.
# Won't do anything if "claimed-villagers-take-damage" is enabled.
# Default: true
claimed-immune-kill-command: true

# Whether villager hoppers should tick and pick up villagers.
# Turning this off will effectively disable villager hoppers.
# Default: true
tick-hoppers: true
# The rate at which villager hoppers should tick. (in ticks)
# You can increase this value to reduce lag, but it will also reduce the speed at which villagers are picked up.
# Default: 20
hopper-tick-rate: 20
# The maximum amount of villager hoppers a chunk can hold.
# You can use this to prevent lag/spam.
# -1 will disable the limit.
# Default: -1
hopper-limit-per-chunk: -1

# Whether baby villagers should be ignored by villager hoppers.
# Default: true
ignore-baby-villagers: true
# Whether claimed villagers should be ignored by villager hoppers.
# Default: true
ignore-claimed-villagers: true
# Whether to register the villager hopper recipe.
# If this is disabled, players won't be able to craft villager hoppers regularly.
# Default: true
hopper-recipe: true
# Weather to display the emerald frame on villager hoppers.
# WARNING: It might be hard to distinguish villager hoppers from regular hoppers when this setting is disabled.
# Default: true
hopper-block-display: true
# The range at which the emerald frame should be displayed.
# Default: 1.0
hopper-block-display-view-range: 1.0

# How many trading partners a player can have.
# Default: 10
partner-limit-per-player: 10
# Whether to validate partner names.
# If this is enabled, players can only add players that played on the server before as trading partners.
# If this is disabled, players can add any name as a trading partner, even if that player doesn't exist.
# Default: true
validate-partner-names: true

# Set a custom model data for the picked up villagers based on professions.
# This is useful for resource packs that want to change the model/texture of picked up villagers.
# Value 0 will not change the model.
custom-model-datas:
  baby: 0
  zombie: 0
  librarian: 0